name: 'Get & Cache Dependencies'
description: 'Get Dependencies and cache them'
inputs:
  cache-hit: 
    description: 'Cache hit'
    required: true
    default: 'true'
outputs:
  cache-hit: 
    description: 'Cache hit'
    value: ${{ steps.cache.outputs.cache-hit }}        
runs:
  using: "composite"
  steps:
      - name: Cache dependencies
        if: inputs.cache-hit == 'true'
        id: cache
        uses: actions/cache@v5
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        id: install
        if: steps.cache.outputs.cache-hit != 'true' || inputs.cache-hit == 'false'
        run: |
            npm ci
            echo "cache-hit=false" >> $GITHUB_OUTPUT
        shell: bash